#!/bin/bash 

if [ $# -lt 1 ]; then 
  echo "Usage: $(basename $0) <username>"
  exit 1
fi

username=$1

source pma_util

readPass "$username"

resp=$(curl -s -X post https://pma.dextra.com.br/pma/services/obter_token -d username=$username\&password=$password)

handlePmaResponse "$resp"

if [ $response_code != '0' ]; then
   echo "$response_error"
   exit 1
fi

echo $resp | xpath -q -e '//token/text()' > $HOME/.pma_token
cat $HOME/.pma_token
