#!/bin/bash

if [ $# -lt 1 ]; then 
  echo "Usage: $(basename $0) <projectid> [<projectid> ...]"
  exit 1
fi
source pma_util

function tasks() {
  projectid=$1

  resp=$(curl -s -X post https://pma.dextra.com.br/pma/services/listar_atividades -d token=$(cat $HOME/.pma_token)\&projeto=$projectid)

  handlePmaResponse "$resp"

  if [ $response_code != '0' ]; then
     echo "$response_error"
     return
  fi

  list=$(echo $resp | xpath -q -e "//atividade/nome/text() | //atividade/id/text()" | sed "s/ /_/g")

  group "$list" 2
  echo "$group_result"
}

if [ $# -gt 1 ]; then
  for k in $@; do
    echo "Project $k"
    tasks "$k"
    echo
  done
else
  tasks "$1"
fi
