#!/bin/bash

today=$(date +'%F')

curl -s -X post https://pma.dextra.com.br/pma/services/criar_apontamento_diario -d token=$(cat $HOME/.pma_token)\&data=$today\&inicio=09:00\&intervalo=01:00\&fim=18:00
