#!/bin/bash 

list=$(curl -s -X post https://pma.dextra.com.br/pma/services/listar_projetos -d token=$(cat $HOME/.pma_token) | xpath -q -e "//projeto/cliente/text() | //projeto/nome/text() | //projeto/id/text()" | sed "s/ /_/g")

source pma_util
group "$list" 3
echo "$group_result"
