#!/bin/bash

function usage() {
  cat <<END
   -h                 : This help
   -d <date>          : Date to create (yyyy-MM-dd)
   -s <start time>    : Start time (HH:mm)
   -e <end time>      : End time (HH:mm)
   -i <interval time> : Interval time (HH:mm)
END
}

if [ $# -eq 0 ]; then
  usage
  exit 1
fi

while getopts "h?dsei:" opt; do
    case "$opt" in
    h|\?)
        usage
        exit 0
        ;;
    d)  date=$OPTARG 
        ;;
    s)  starttime=$OPTARG
        ;;
    e)  endtime=$OPTARG
        ;;
    i)  interval=$OPTARG
        ;;

    esac
done

today=$(date +'%F')

curl -s -X post https://pma.dextra.com.br/pma/services/criar_apontamento_diario -d token=$(cat $HOME/.pma_token)\&data=$date\&inicio=$starttime\&intervalo=$interval\&fim=$endtime

